version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: discount_postgres
    environment:
      POSTGRES_USER: discount_user
      POSTGRES_PASSWORD: discount_pass
      POSTGRES_DB: discount_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U discount_user -d discount_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local